service: keyboard-dojo

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - !GetAtt UsersTable.Arn
        - !GetAtt LessonsTable.Arn
        - !GetAtt ProgressTable.Arn
        - !Sub "${UsersTable.Arn}/index/*"
        - !Sub "${LessonsTable.Arn}/index/*"
        - !Sub "${ProgressTable.Arn}/index/*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true

functions:
  healthCheck:
    handler: src/functions/healthCheck.handler
    events:
      - http:
          path: /health
          method: get
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH

    LessonsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-lessons
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: lessonId
            AttributeType: S
        KeySchema:
          - AttributeName: lessonId
            KeyType: HASH

    ProgressTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-progress
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH 